- name: Check if PhpStorm is already installed
  stat:
    path: "{{ phpstorm_bin }}"
  register: __phpstorm_bin
  tags:
    - phpstorm

- name: Download PhpStorm archive
  get_url:
    url: "{{ phpstorm_download_url }}"
    dest: /tmp/phpstorm.tar.gz
    checksum: "{{ phpstorm_checksum }}"
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm

- name: Ensure phpstorm folder exists
  file:
    path: "{{ phpstorm_path }}"
    state: directory
  tags:
    - phpstorm

- name: Extract PhpStorm archive
  unarchive:
    src: /tmp/phpstorm.tar.gz
    dest: "{{ phpstorm_path }}"
    remote_src: yes
  when: not __phpstorm_bin.stat.exists
  tags:
    - phpstorm

- name: Remove PhpStorm archive
  file:
    path: /tmp/phpstorm.tar.gz
    state: absent
  tags:
    - phpstorm

- name: Ensure launcher destination folder exists
  file:
    path: "{{ home_directory }}/.local/share/applications/"
    state: directory
  tags:
    - phpstorm

- name: Copy launcher
  template:
    src: phpstorm.desktop.j2
    dest: "{{ home_directory }}/.local/share/applications/phpstorm.desktop"
  tags:
    - phpstorm

- name: Add launcher to favorite-apps
  command: "gsettings set org.gnome.shell favorite-apps \"['ubiquity.desktop', 'firefox.desktop', 'phpstorm.desktop', 'org.gnome.Nautilus.desktop']\""
  ignore_errors: yes
  tags:
    - phpstorm
