- name: Ensure composer path folder exists
  file:
    path: "{{ composer_path }}"
    state: directory
  tags:
    - composer

- name: Check if Composer is already installed
  stat:
    path: "{{ composer_bin }}"
  register: __composer_bin
  tags:
    - composer

- name: Get Composer installer signature
  uri:
    url: https://composer.github.io/installer.sig
    return_content: yes
  register: composer_installer_signature
  when: not __composer_bin.stat.exists
  tags:
    - composer

- name: Download Composer installer
  get_url:
    url: https://getcomposer.org/installer
    dest: /tmp/composer-installer.php
    checksum: "sha384:{{ composer_installer_signature.content }}"
  when: not __composer_bin.stat.exists
  tags:
    - composer

- name: Install Composer
  command: 'php{{ php_version }} /tmp/composer-installer.php --install-dir="{{ composer_path }}" --filename="composer"'
  when: not __composer_bin.stat.exists
  tags:
    - composer
  become: true

- name: Remove Composer installer
  file:
    path: /tmp/composer-installer.php
    state: absent
  tags:
    - composer
