- name: Register user home directory
  command: echo ~
  register: home_directory
  tags:
    - always

- name: Store user home directory globally
  set_fact:
    home_directory: "{{ home_directory.stdout }}"
  tags:
    - always

- name: Configure APT to use HTTP proxy
  blockinfile:
    path: /etc/apt/apt.conf.d/99proxy.conf
    create: yes
    block: |
      Acquire {
        HTTP::proxy "{{ ansible_env.HTTP_PROXY }}";
        HTTPS::proxy "{{ ansible_env.HTTPS_PROXY }}";
      }
  when: "'HTTP_PROXY' in ansible_env"
  tags:
    - always
  become: true

- name: Install common packages
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - curl
    - git
    - nano
    - rsync
    - unzip
    - wget
  become: true
