- name: Install Docker
  apt:
    name: "{{ item }}"
    update_cache: yes
    state: latest
  with_items:
    - docker.io
  tags:
    - docker
  become: true

- name: Configure Docker to use HTTP proxy
  blockinfile:
    path: /etc/systemd/system/docker.service.d/http-proxy.conf
    create: yes
    block: |
      [Service]
      Environment="HTTP_PROXY={{ ansible_env.HTTP_PROXY }}"
  when: "'HTTP_PROXY' in ansible_env"
  tags:
    - docker
  become: true

- name: Enable and start Docker service
  systemd:
    name: docker
    enabled: yes
    masked: no
    state: started
    daemon_reload: yes
  tags:
    - docker
  become: true

- name: Add the default user to the docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: true
  tags:
    - docker
  become: true
